# Generated by Django 5.2.7 on 2025-10-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("university_name", models.CharField(max_length=255)),
                ("country_code", models.CharField(default="LB", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_student_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="university_domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[("link", "Link"), ("otp", "One-Time Password")],
                        default="link",
                        max_length=8,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("university_domain", models.CharField(blank=True, max_length=255)),
                ("otp_code_hash", models.CharField(blank=True, max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_ua", models.CharField(blank=True, max_length=512)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="users_verif_user_id_aba751_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="users_verif_expires_fe97fb_idx"
                    ),
                    models.Index(fields=["email"], name="users_verif_email_624495_idx"),
                ],
            },
        ),
    ]
