# Generated by Django 5.2.7 on 2025-10-17 11:11

from django.db import migrations


DOMAIN_DATA = [
    ("mail.aub.edu", "American University of Beirut"),
    ("aub.edu.lb", "American University of Beirut"),
    ("lau.edu.lb", "Lebanese American University"),
    ("usj.edu.lb", "Saint Joseph University of Beirut"),
    ("usek.edu.lb", "Holy Spirit University of Kaslik"),
    ("balamand.edu.lb", "University of Balamand"),
    ("ndu.edu.lb", "Notre Dame University - Louaize"),
    ("hu.edu.lb", "Haigazian University"),
    ("ul.edu.lb", "Lebanese University"),
]


def seed_domains(apps, schema_editor):
    domain_model = apps.get_model("users", "UniversityDomain")
    for domain, name in DOMAIN_DATA:
        domain_model.objects.get_or_create(
            domain=domain,
            defaults={
                "university_name": name,
                "country_code": "LB",
                "is_active": True,
            },
        )


def unseed_domains(apps, schema_editor):
    domain_model = apps.get_model("users", "UniversityDomain")
    domain_model.objects.filter(domain__in=[domain for domain, _ in DOMAIN_DATA]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_universitydomain_profile_email_verified_at_and_more"),
    ]

    operations = [migrations.RunPython(seed_domains, reverse_code=unseed_domains)]
