# Generated by Django 5.2.7 on 2025-11-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_property"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[("SINGLE", "Single"), ("DOUBLE", "Double")],
                        max_length=10,
                    ),
                ),
                ("total_rooms", models.PositiveIntegerField()),
                ("available_rooms", models.PositiveIntegerField()),
                (
                    "price_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["room_type"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="additional_services",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="has_cleaning_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="has_electricity_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["owner", "created_at"], name="users_prope_owner_i_1d2456_idx"
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="users.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="users.property",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyroom",
            unique_together={("property", "room_type", "notes")},
        ),
    ]
