# Generated by Django 5.2.6 on 2025-10-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_date_of_birth_profile_profile_completed_and_more'),
    ]

    operations = [
    ]
