# Generated by Django 5.2.7 on 2025-11-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20251020_0904"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="property_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("DOUBLE", "Double"),
                            ("SUITE", "Suite"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("available_quantity", models.PositiveIntegerField(default=0)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("electricity_included", models.BooleanField(default=False)),
                ("cleaning_included", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="room_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="property",
            name="cleaning_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="cover_image",
            field=models.FileField(blank=True, null=True, upload_to="property_covers/"),
        ),
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="electricity_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["owner", "created_at"], name="users_prope_owner_i_1d2456_idx"
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="users.property",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="users.property",
            ),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="users.room",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "uploaded_at"],
                name="users_prope_propert_edb5ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["property", "name"], name="users_room_propert_4c5994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["property", "room_type"], name="users_room_propert_6e07cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomimage",
            index=models.Index(
                fields=["room", "uploaded_at"], name="users_roomi_room_id_47624b_idx"
            ),
        ),
    ]
