# Generated by Django 5.2.7 on 2025-11-04 15:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_owner_dorm_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingrequest',
            new_name='users_booki_room_id_2bafc9_idx',
            old_name='users_book_room_id_5c41d4_idx',
        ),
        migrations.RenameIndex(
            model_name='dorm',
            new_name='users_dorm_propert_9c7781_idx',
            old_name='users_dorm_propert_0a0e52_idx',
        ),
        migrations.RenameIndex(
            model_name='dormroom',
            new_name='users_dormr_dorm_id_b599c4_idx',
            old_name='users_dorm_dorm_id_6f0ced_idx',
        ),
        migrations.AlterField(
            model_name='dorm',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models._dorm_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='dormimage',
            name='image',
            field=models.ImageField(upload_to=apps.users.models._dorm_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='dormroomimage',
            name='image',
            field=models.ImageField(upload_to=apps.users.models._room_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
