# Generated by Django 5.2.8 on 2025-11-18 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_users_book_room_id_5c41d4_idx_users_booki_room_id_2bafc9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.PositiveSmallIntegerField(default=0)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_favorited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_matches_as_match', to='users.profile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_matches_as_seeker', to='users.profile')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'indexes': [models.Index(fields=['seeker', '-compatibility_score'], name='users_roomm_seeker__fd87dc_idx'), models.Index(fields=['seeker', 'is_favorited'], name='users_roomm_seeker__0f78d7_idx')],
                'unique_together': {('seeker', 'match')},
            },
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_schedule', models.CharField(choices=[('EARLY_BIRD', 'Early Bird (Sleep before 10 PM)'), ('NIGHT_OWL', 'Night Owl (Sleep after midnight)'), ('FLEXIBLE', 'Flexible')], default='FLEXIBLE', max_length=20)),
                ('cleanliness_level', models.CharField(choices=[('VERY_CLEAN', 'Very Clean'), ('MODERATELY_CLEAN', 'Moderately Clean'), ('RELAXED', 'Relaxed')], default='MODERATELY_CLEAN', max_length=20)),
                ('social_preference', models.CharField(choices=[('VERY_SOCIAL', 'Very Social'), ('MODERATELY_SOCIAL', 'Moderately Social'), ('PREFER_QUIET', 'Prefer Quiet')], default='MODERATELY_SOCIAL', max_length=20)),
                ('study_habits', models.CharField(choices=[('LIBRARY', 'Study at Library'), ('DORM', 'Study in Dorm'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('interests', models.TextField(blank=True, help_text='Comma-separated hobbies/interests (e.g., sports, music, gaming)')),
                ('budget_range', models.CharField(blank=True, help_text='Monthly budget for accommodation', max_length=100)),
                ('preferred_gender', models.CharField(blank=True, help_text='Preferred roommate gender (optional)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profile is visible to other students')),
                ('bio', models.TextField(blank=True, help_text='Short bio about yourself', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'is_active'], name='users_roomm_profile_da9e12_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Introduction message', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('response_message', models.TextField(blank=True, max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_requests', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_roommate_requests', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='users_roomm_sender__16d498_idx'), models.Index(fields=['receiver', 'status'], name='users_roomm_receive_efbc99_idx')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
