# Generated by Django 5.2.8 on 2025-11-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_users_book_room_id_5c41d4_idx_users_booki_room_id_2bafc9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats_available', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_rides', to='users.profile')),
            ],
        ),
    ]
