# Generated by Django 5.2.8 on 2025-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_carpoolride'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolride',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpoolride',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
