# Generated by Django 5.2.6 on 2025-11-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_roommatematch_roommateprofile_roommaterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommateprofile',
            name='preferred_gender',
        ),
    ]
