# Generated by Django 5.2.6 on 2025-11-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_roommateprofile_preferred_gender'),
        ('users', '0014_carpoolbooking'),
    ]

    operations = [
    ]
