# Generated by Django 5.2.7 on 2025-10-18 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_university_domains(apps, schema_editor):
    UniversityDomain = apps.get_model("users", "UniversityDomain")
    domains = [
        ("mail.aub.edu", "American University of Beirut"),
        ("aub.edu.lb", "American University of Beirut"),
        ("lau.edu.lb", "Lebanese American University"),
        ("ul.edu.lb", "Lebanese University"),
        ("usj.edu.lb", "Saint Joseph University of Beirut"),
        ("usek.edu.lb", "Holy Spirit University of Kaslik"),
        ("ndu.edu.lb", "Notre Dame University-Louaize"),
        ("balamand.edu.lb", "University of Balamand"),
        ("hu.edu.lb", "Haigazian University"),
    ]
    for domain, name in domains:
        UniversityDomain.objects.get_or_create(domain=domain, defaults={"university_name": name})


def remove_university_domains(apps, schema_editor):
    UniversityDomain = apps.get_model("users", "UniversityDomain")
    UniversityDomain.objects.filter(
        domain__in=[
            "mail.aub.edu",
            "aub.edu.lb",
            "lau.edu.lb",
            "ul.edu.lb",
            "usj.edu.lb",
            "usek.edu.lb",
            "ndu.edu.lb",
            "balamand.edu.lb",
            "hu.edu.lb",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_student_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=255)),
                ("otp_hash", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("otp", "OTP")], default="otp", max_length=20
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("resend_count", models.PositiveIntegerField(default=0)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_ua", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UniversityDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("university_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["domain"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="users_unive_domain_2ea709_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="university_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="users.universitydomain",
            ),
        ),
        migrations.RunPython(seed_university_domains, remove_university_domains),
    ]
