# Generated by Django 5.2.7 on 2025-10-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_emailotp_delete_emailverificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("SEEKER", "SEEKER"), ("OWNER", "OWNER")],
                        max_length=10,
                    ),
                ),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university_domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_registrations",
                        to="users.universitydomain",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_pendi_email_2ec85b_idx"),
                    models.Index(fields=["phone"], name="users_pendi_phone_790b7c_idx"),
                ],
            },
        ),
    ]
