# Generated by Django 5.2.7 on 2025-10-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_pendingregistration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailOTP",
        ),
        migrations.DeleteModel(
            name="PendingRegistration",
        ),
    ]
