# Generated by Django 5.2.8 on 2025-11-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0011_rename_users_book_room_id_5c41d4_idx_users_booki_room_id_2bafc9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dormimage",
            options={"managed": True, "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dormroomimage",
            options={"managed": True, "ordering": ["-created_at"]},
        ),
        migrations.AlterModelTable(
            name="dormimage",
            table="users_dormimage",
        ),
        migrations.AlterModelTable(
            name="dormroomimage",
            table="users_dormroomimage",
        ),
    ]
